### ISSUE TITLE
RTNETLINK1 answers: No such file or directory

### ISSUE THREAD

**Issue by navinagaraj** [tedfelix/acpid2#1]
Hi,

I have an error while restarting acpid2. I shared the log below.

------------------------------------------------------------------------------------------------
/etc/init.d/S12-acpid2 restart
Stopping acpid: [OK]
Starting acpid: [OK]
# RTNETLINK1 answers: No such file or directory
acpid: error talking to the kernel via netlink
--------------------------------------------------------------------------------------------------

**Comment by tedfelix** [comment]
We've asked netlink to CTRL_CMD_GETFAMILY with "acpi_event" as the name and it is saying "No such file or directory".  I've never seen this.  It's as if netlink isn't aware of acpi.  Feels to me like a kernel configuration issue.  Perhaps the acpi portions of the kernel are disabled, or something.  What kernel version are you using?  What distro is this?  Did you build the kernel yourself?

**Comment by navinagaraj** [comment]
Hi,
Yes, I build the kernel myself, I am using the Kernel 5.4.debian distribution.

**Comment by tedfelix** [comment]
Ok.  Do you have CONFIG_ACPI set to "y"?  And what about CONFIG_ACPI_BUTTON?  What is it set to?

And maybe bigger picture, are you sure you even need acpid?  What are you trying to use it for specifically?

**Comment by navinagaraj** [comment]
Thanks for the quick response info @tedfelix.I will check and update you.

**Comment by navinagaraj** [comment]
After set the options  CONFIG_ACPI & CONFIG_ACPI_BUTTON to "y".It's working now. Thanks.
