### ISSUE TITLE
Differences between Sourceforge & github releases

### ISSUE THREAD

**Issue by macmpi** [tedfelix/acpid2#3]
Thanks for 2.0.34 release.
I noticed Sourceforge & Github releases have a few content differences, which may impact some build automation scripts in using one or the other location. In particular Github misses `configure` file for instance.
```
$ diff -qr Github_acpid2-2.0.34/ Sourceforge_acpid-2.0.34/
Only in Sourceforge_acpid-2.0.34/: aclocal.m4
Only in Sourceforge_acpid-2.0.34/: build-aux
Only in Sourceforge_acpid-2.0.34/: config.h
Only in Sourceforge_acpid-2.0.34/: config.h.in
Only in Sourceforge_acpid-2.0.34/: configure
Only in Github_acpid2-2.0.34/: .gitignore
Only in Sourceforge_acpid-2.0.34/kacpimon: Makefile.in
Only in Sourceforge_acpid-2.0.34/: Makefile.in

```
Any specific reason for such differences?
Moving forward, what is the recommended primary repo?
Thanks.

**Comment by tedfelix** [comment]
Those differences only exist in your copy.  Some of those files are build related that are not in the repo.  This is normal.  The .gitignore difference is surprising.  Not sure what's causing that for you.  Try doing a "git checkout ." in each copy and see if that clears it up.

The commit hash for both repos is identical: 1701f8c.  So the contents are exactly the same and cryptographically guaranteed.  Take a look at the file lists at each repo:

- https://github.com/tedfelix/acpid2
- https://sourceforge.net/p/acpid2/code/ci/master/tree/

...and you'll see they are the same.  .gitignore is in both.

I'm going to close this, but feel free to post further questions and I can try to help you get your working copies in sync.

**Comment by macmpi** [comment]
> Those differences only exist in your copy

Those copies are plain uncompressed releases archives form both locations, no other changes or action than uncompressing before diff command.
You may run autoconf before packaging the release on sourceforge, but not on github maybe?

**Comment by tedfelix** [comment]
> You may run autoconf before packaging the release on sourceforge, but not on github maybe?

That is exactly my release process.  autoreconf then make the tarball.  Neither sourceforge nor github reflect that.  So, yeah.  The release tarball does not match what is in version control.  But you can get there by running autoreconf:

```
$ make distclean
$ autoreconf --install --force
$ ./configure
$ make dist
```

Should I add that to the README?

**Comment by macmpi** [comment]
Yes maybe.
What's the recommended primary repo from now on: Github or Sourceforge?

**Comment by tedfelix** [comment]
I'm treating both repos as the same.  The only difference is that SourceForge has the tarballs.  So I guess it is the primary.  I should figure out how to post files on github and then there will be no difference.
